# Generated by Django 3.0.7 on 2020-06-23 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=120, primary_key=True, serialize=False, unique=True)),
                ('nif', models.CharField(max_length=9, unique=True)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('zip_code', models.CharField(max_length=16)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('provider_name', models.CharField(max_length=120)),
                ('provider_nif', models.DecimalField(decimal_places=0, max_digits=9)),
                ('service_value', models.PositiveIntegerField()),
                ('emission_date', models.DateField()),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_explanation', models.TextField(blank=True, null=True)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Client')),
            ],
        ),
    ]
