# Generated by Django 3.0.7 on 2020-06-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200626_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='cid',
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=120, primary_key=True, serialize=False, unique=True),
        ),
    ]
